/**
 * Standardized error codes for API responses
 * Format: ENTITY_ACTION_ERROR
 */

// Auth errors
export const AUTH_USERNAME_TAKEN = 'AUTH_USERNAME_TAKEN';
export const AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';
export const AUTH_JWT_SECRET_MISSING = 'AUTH_JWT_SECRET_MISSING';
export const AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID';
export const AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED';

// User errors
export const USER_NOT_FOUND = 'USER_NOT_FOUND';

// Message errors
export const MESSAGE_DAILY_LIMIT_EXCEEDED = 'MESSAGE_DAILY_LIMIT_EXCEEDED';
export const MESSAGE_SEND_FAILED = 'MESSAGE_SEND_FAILED';

// Validation errors
export const VALIDATION_ERROR = 'VALIDATION_ERROR';

export default {
  AUTH_USERNAME_TAKEN,
  AUTH_INVALID_CREDENTIALS,
  AUTH_JWT_SECRET_MISSING,
  AUTH_TOKEN_INVALID,
  AUTH_UNAUTHORIZED,
  USER_NOT_FOUND,
  MESSAGE_DAILY_LIMIT_EXCEEDED,
  MESSAGE_SEND_FAILED,
  VALIDATION_ERROR,
};
